[default]
API_KEY = "dQt5sBVViAjMpsiFj4a2KwF7S"
API_SECRET = "DYSvmwE0IWXqounHpyJFuoCNoLzS4oPGyPtS92aDxNZBTIRqen"
TOKEN = "1118850823080038403-xTUSHoez2IADnaUuJGvVR4MjbrkMYH"
TOKEN_SECRET = "kePnG3XalxYVhxd2cBap0YBrAkrrTuCCts4bXxuTBhnCQ"