[default]
API_KEY = "jIo8NOJPv5RlOHkKQSdN74ZWQ"
API_SECRET = "NvP4rl2r3uj7Gdt9bNirQSvwo7Vab3VjdEDmyvqUbmyBKLIVtk"
TOKEN = "1118850823080038403-8ZPRu0KvN2WN5wuG6W0g6UlAhD8uaV"
TOKEN_SECRET = "22LaDm4ijbnlNAlHonaDXLOVtTgOcd9fC8LY3fi2nhtbO"